import firstImage from '../assets/first.jpg';
import secondImage from '../assets/second.jpg';
import thirdImage from '../assets/third.jpg';
import fourthImage from '../assets/fourth.jpg';
import fifthImage from '../assets/fifth.jpg';
import sixthImage from '../assets/sixth.jpg';
import seventhImage from '../assets/seventh.jpg';
import eightImage from '../assets/eight.jpg';
import ninthImage from '../assets/ninth.jpg';
import tenthImage from '../assets/tenth.jpg';
import elevenImage from '../assets/eleven.jpg';
import twelveImage from '../assets/twelve.jpg';
import thirteenImage from '../assets/thirteen.jpg';
import fourtheenImage from '../assets/fourtheen.jpg';
import fiftheenImage from '../assets/fiftheen.jpg';
import sixtheenImage from '../assets/sixtheen.jpg';
import seventeenImage from '../assets/seventeen.jpg';

const products = [
  {
    id: 1,
    name: "Leather Handbag",
    category: "CABLUKI",
    category_ua: "КАБЛУКИ",
    category_ru: "КАБЛУКИ",
    description: "Stylish leather handbag with ample storage space.",
    description_ua: "Стильна шкіряна сумка з великим обсягом.",
    description_ru: "Стильная кожаная сумка с большим объемом.",
    price: 2999.62,
    oldPrice: 3749.62,
    image: firstImage,
    color: "BLACK",
    color_ua: "ЧОРНИЙ",
    color_ru: "ЧЕРНЫЙ",
    author: "admin",
    otherImages: [firstImage, secondImage, elevenImage, fourthImage],
  },
  {
    id: 2,
    name: "Evening Gown",
    category: "SABOTY",
    category_ua: "САБОТИ",
    category_ru: "САБОТЫ",
    description: "Elegant evening gown for special occasions.",
    description_ua: "Елегантна вечірня сукня для особливих подій.",
    description_ru: "Элегантное вечернее платье для особых событий.",
    price: 5624.62,
    oldPrice: 7499.62,
    image: secondImage,
    color: "RED",
    color_ua: "ЧЕРВОНИЙ",
    color_ru: "КРАСНЫЙ",
    otherImages: [secondImage, firstImage, thirdImage, fifthImage],
  },
  {
    id: 3,
    name: "Gold Necklace",
    category: "SNEAKERS",
    category_ua: "КРОСІВКИ",
    category_ru: "КРОССОВКИ",
    description: "Exquisite gold necklace with intricate design.",
    description_ua: "Вишукане золоте кольє зі складним дизайном.",
    description_ru: "Изысканное золотое колье с замысловатым дизайном.",
    price: 7499.62,
    image: thirdImage,
    color: "GOLD",
    color_ua: "ЗОЛОТИЙ",
    color_ru: "ЗОЛОТОЙ",
    otherImages: [thirdImage, seventeenImage, fourthImage, sixthImage],
  },
  {
    id: 4,
    name: "Matte Lipstick",
    category: "SLIPERY",
    category_ua: "ТАПОЧКИ",
    category_ru: "ТАПОЧКИ",
    description: "Long-lasting matte lipstick in various shades.",
    description_ua: "Стійка матова помада у різних відтінках.",
    description_ru: "Стойкая матовая помада в разных оттенках.",
    price: 749.62,
    image: fourthImage,
    color: "RED",
    color_ua: "ЧЕРВОНИЙ",
    color_ru: "КРАСНЫЙ",
    otherImages: [fourthImage, firstImage, fifthImage, thirteenImage],
  },
  {
    id: 5,
    name: "Silk Scarf",
    category: "STILETTO",
    category_ua: "ШПИЛІ",
    category_ru: "КАБЛУКИ",
    description: "Luxurious silk scarf with vibrant colors.",
    description_ua: "Розкішний шовковий шарф з яскравими кольорами.",
    description_ru: "Роскошный шелковый шарф с яркими цветами.",
    price: 1124.62,
    oldPrice: 1499.62,
    image: fifthImage,
    color: "BLUE",
    color_ua: "СИНІЙ",
    color_ru: "СИНИЙ",
    otherImages: [fifthImage, thirdImage, sixthImage, twelveImage],
  },
  {
    id: 6,
    name: "Cocktail Dress",
    category: "FLIP-FLOPS",
    category_ua: "ТЕПЛІ ЧЕБОТИ",
    category_ru: "ТЕПЛЫЕ БОТИНКИ",
    description: "Chic cocktail dress for parties and events.",
    description_ua: "Шикарна коктейльна сукня для вечірок та подій.",
    description_ru: "Шикарное коктейльное платье для вечеринок и мероприятий.",
    price: 3374.62,
    image: sixthImage,
    color: "BLACK",
    color_ua: "ЧОРНИЙ",
    color_ru: "ЧЕРНЫЙ",
    otherImages: [sixthImage, fiftheenImage, seventhImage, ninthImage],
  },
  {
    id: 7,
    name: "Diamond Earrings",
    category: "LOAFERS",
    category_ua: "ЛОФЕРИ",
    category_ru: "ЛОФЕРЫ",
    description: "Sparkling diamond earrings that add elegance to any outfit.",
    description_ua: "Сяючі діамантові сережки для елегантності.",
    description_ru: "Сверкающие бриллиантовые серьги для элегантности.",
    price: 11249.62,
    oldPrice: 13124.62,
    image: seventhImage,
    color: "SILVER",
    color_ua: "СРІБНИЙ",
    color_ru: "СЕРЕБРЯНЫЙ",
    otherImages: [seventhImage, fifthImage, eightImage, tenthImage],
  },
  {
    id: 8,
    name: "Foundation",
    category: "ANKLE BOOTS",
    category_ua: "БОТІНКИ НА БІРКІ",
    category_ru: "БОТИНКИ НА ПОДЪЕМЕ",
    description: "High-coverage foundation for a flawless finish.",
    description_ua: "Тональна основа з високим покриттям для бездоганного вигляду.",
    description_ru: "Тональная основа с высоким покрытием для безупречного вида.",
    price: 1499.62,
    image: eightImage,
    color: "BEIGE",
    color_ua: "БЕЖЕВИЙ",
    color_ru: "БЕЖЕВЫЙ",
    otherImages: [eightImage, sixthImage, ninthImage, elevenImage],
  },
  {
    id: 9,
    name: "Sunglasses",
    category: "PUMPS",
    category_ua: "ТУФЛІ",
    category_ru: "ТУФЛИ",
    description: "Trendy sunglasses with UV protection.",
    description_ua: "Модні сонцезахисні окуляри з UV захистом.",
    description_ru: "Модные солнцезащитные очки с UV защитой.",
    price: 1874.62,
    image: ninthImage,
    color: "BLACK",
    color_ua: "ЧОРНИЙ",
    color_ru: "ЧЕРНЫЙ",
    otherImages: [ninthImage, seventhImage, fourtheenImage, twelveImage],
  },
  {
    id: 10,
    name: "Casual Pants",
    category: "FLATS",
    category_ua: "ПЛАТФОРМИ",
    category_ru: "ПЛАТФОРМЫ",
    description: "Comfortable maxi dress for casual outings.",
    description_ua: "Комфортна максі-сукня для повсякденних прогулянок.",
    description_ru: "Комфортное макси-платье для повседневных прогулок.",
    price: 2249.62,
    oldPrice: 2999.62,
    image: tenthImage,
    color: "GREEN",
    color_ua: "ЗЕЛЕНИЙ",
    color_ru: "ЗЕЛЕНЫЙ",
    otherImages: [tenthImage, sixtheenImage, elevenImage, thirteenImage],
  },
];

export default products;
